@startuml
left to right direction

actor Productor
actor PersonalCampo

rectangle Ganadapp {

  usecase "Gestionar Ganado" as UC1
  usecase "Registrar Evento Sanitario" as UC2
  usecase "Consultar Trazabilidad" as UC3
  usecase "Gestionar Stock" as UC4
  usecase "Generar Alertas" as UC5
  usecase "Autenticación" as UC6
}

Productor --> UC1
Productor --> UC3
Productor --> UC4

PersonalCampo --> UC1
PersonalCampo --> UC2
PersonalCampo --> UC4

UC5 ..> UC4 : incluye
UC5 ..> UC2 : incluye

@enduml