@startuml
left to right direction

actor Sistema
actor Productor

rectangle "Sistema de Alertas" {

  usecase "Evaluar Stock" as UC1
  usecase "Evaluar Eventos Sanitarios" as UC2
  usecase "Detectar Condiciones Críticas" as UC3
  usecase "Generar Alerta" as UC4
  usecase "Notificar Usuario" as UC5
}

Sistema --> UC1
Sistema --> UC2

UC1 ..> UC3 : <<include>>
UC2 ..> UC3 : <<include>>

UC3 ..> UC4 : <<include>>
UC4 ..> UC5 : <<include>>

Productor <-- UC5

@enduml