@startuml
left to right direction

actor Productor
actor PersonalCampo

rectangle "Gestión de Ganado" {

  usecase "Registrar Animal" as UC1
  usecase "Actualizar Animal" as UC2
  usecase "Consultar Animal" as UC3
  usecase "Listar Ganado" as UC4
  usecase "Cambiar Estado Sanitario" as UC5
}

Productor --> UC1
Productor --> UC2
Productor --> UC3
Productor --> UC4

PersonalCampo --> UC1
PersonalCampo --> UC5

UC2 ..> UC3 : <<include>>
UC5 ..> UC3 : <<extend>>

@enduml