@startuml
left to right direction

actor Usuario

rectangle "Autenticación y Control de Acceso" {

  usecase "Ingresar Credenciales" as UC1
  usecase "Validar Usuario" as UC2
  usecase "Asignar Rol" as UC3
  usecase "Iniciar Sesión" as UC4
  usecase "Cerrar Sesión" as UC5
}

Usuario --> UC1
UC1 ..> UC2 : <<include>>
UC2 ..> UC3 : <<include>>
UC3 ..> UC4 : <<include>>

Usuario --> UC5

@enduml